name: flutter_clean_lint
description: "Custom lints for Flutter"
version: 0.1.8
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  analyzer: 8.4.0
  analyzer_plugin: 0.13.10
  custom_lint_builder: ^0.8.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
